# Generated by Django 3.1.2 on 2020-10-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(db_index=True, default=-1)),
                ('min_len', models.IntegerField(db_index=True)),
                ('max_len', models.IntegerField(db_index=True)),
                ('min_rank', models.IntegerField(db_index=True)),
                ('max_rank', models.IntegerField(db_index=True)),
                ('correct', models.IntegerField(db_index=True, default=0)),
                ('wrong', models.IntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('email', models.CharField(db_index=True, max_length=200)),
                ('password', models.CharField(db_index=True, max_length=35)),
                ('start', models.IntegerField(default=0)),
                ('test_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='WordInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=50)),
                ('uid', models.IntegerField(db_index=True)),
                ('correct', models.IntegerField(db_index=True, default=0)),
                ('wrong', models.IntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=50)),
                ('length', models.IntegerField(default=0)),
            ],
        ),
    ]
