# Generated by Django 3.1.2 on 2020-10-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201010_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='current_word_idx',
            field=models.IntegerField(default=0),
        ),
    ]
