# Generated by Django 3.1.2 on 2020-10-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_test_current_word_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='total_words',
            field=models.IntegerField(default=0),
        ),
    ]
